spring.application.name=api-gateway

server.port=${PORT:8080}

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=https://user-service1-midk.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=https://product-service-e3qx.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=https://cart-service-47qe.onrender.com
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/cart/**

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false
